
const views=["home","english","english-learn","math","math-rows-menu","math-understand-menu","math-memorize-menu","math-test-menu","math-play","sequence","memorize","progress","rewards"];
function showView(v){views.forEach(x=>document.querySelector(`#${x}-view`)?.classList.add("hidden"));document.querySelector(`#${v}-view`)?.classList.remove("hidden");document.querySelectorAll(".tabbar button").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="math")renderMathWorld();if(v==="progress")renderProgress();if(v==="rewards")renderRewards()}
function renderProfiles(){const box=document.querySelector("#profile-list");box.innerHTML="";db.profiles.forEach(p=>{const b=document.createElement("button");b.className="profile-btn";b.innerHTML=`<div class="av">${p.avatar}</div><strong>${p.name}</strong><small>${p.theme==="cats"?"🐱 Katzenparadies":"⚽ Fußballakademie"}</small>`;b.onclick=()=>chooseProfile(p.id);box.appendChild(b)})}
function chooseProfile(id){db.activeProfileId=id;saveDB();document.querySelector("#profile-screen").classList.add("hidden");document.querySelector("#main-screen").classList.remove("hidden");renderHome()}
function renderHome(){const p=profile();if(!p)return;ensureMath(p);saveDB();const cats=p.theme==="cats";document.querySelector("#profile-chip").textContent=`${p.avatar} ${p.name}`;document.querySelector("#welcome-name").textContent=`Hallo ${p.name}! 👋`;document.querySelector("#world-badge").textContent=cats?"🐱":"⚽";document.querySelector("#reward-home-icon").textContent=cats?"🐱":"⚽";document.querySelector("#reward-home-text").textContent=cats?"Baue dein Katzenparadies aus.":"Baue deine Fußballakademie aus.";document.querySelector("#mission-copy").textContent=cats?"Mimi wartet auf neue Pfoten.":"Der Trainer wartet auf dein Training.";document.querySelector("#home-xp").textContent=p.xp||0;document.querySelector("#home-streak").textContent=p.streak||0;document.querySelector("#home-today").textContent=p.today||0}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
document.querySelectorAll(".back").forEach(b=>b.onclick=()=>showView(b.dataset.back||"home"));
document.querySelector("#profile-chip").onclick=()=>{document.querySelector("#main-screen").classList.add("hidden");document.querySelector("#profile-screen").classList.remove("hidden");renderProfiles()};
document.querySelector("#add-profile").onclick=()=>document.querySelector("#profile-modal").classList.remove("hidden");
document.querySelector("#profile-cancel").onclick=()=>document.querySelector("#profile-modal").classList.add("hidden");
document.querySelector("#profile-form").onsubmit=e=>{e.preventDefault();const name=document.querySelector("#profile-name").value.trim();if(!name)return;db.profiles.push({id:"p_"+Date.now(),name,avatar:document.querySelector("#profile-avatar").value,theme:document.querySelector("#profile-theme").value,xp:0,streak:0,today:0,englishCount:0,mathCount:0,math:{}});saveDB();document.querySelector("#profile-modal").classList.add("hidden");e.target.reset();renderProfiles()};
renderProfiles();if(db.activeProfileId&&profile())chooseProfile(db.activeProfileId);
/* Service Worker temporarily disabled in V12.6 to prevent stale mixed versions. */
