
let WORDS=[],engSession=[],engPos=0;
async function loadWords(){WORDS=await fetch("data/vokabeln.json").then(r=>r.json());renderUnits()}
function renderUnits(){const g={};WORDS.forEach(w=>{const k=`${w.class}|${w.unit}`;g[k]??={class:w.class,unit:w.unit,count:0};g[k].count++});const box=document.querySelector("#english-units");box.innerHTML="";Object.values(g).forEach(x=>{const b=document.createElement("button");b.className="unit-card";b.innerHTML=`<span class="eyebrow">Klasse ${x.class}</span><br><strong>${x.unit}</strong><p>${x.count} Wörter</p>`;b.onclick=()=>startEnglish(x.class,x.unit);box.appendChild(b)})}
function startEnglish(c,u){engSession=WORDS.filter(w=>w.class===c&&w.unit===u).sort(()=>Math.random()-.5).slice(0,20);engPos=0;showView("english-learn");renderEnglish()}
function norm(s){return String(s||"").toLowerCase().trim().replace(/^\(to\)\s*/,"").replace(/[.,!?;:]/g,"").replace(/\s+/g," ")}
function variants(s){const n=norm(s),a=new Set([n]);if(n.startsWith("to "))a.add(n.slice(3));return [...a]}
function renderEnglish(){const w=engSession[engPos];if(!w){showView("english");return}document.querySelector("#eng-title").textContent=`Klasse ${w.class} · ${w.unit}`;document.querySelector("#eng-counter").textContent=`${engPos+1} / ${engSession.length}`;document.querySelector("#eng-de").textContent=w.de;document.querySelector("#eng-answer").value="";document.querySelector("#eng-feedback").textContent="";document.querySelector("#eng-hint-text").textContent="Nur bei Bedarf öffnen.";document.querySelector("#eng-answer").focus()}
document.querySelector("#eng-check").onclick=()=>{const w=engSession[engPos];if(!w)return;const ok=variants(w.en).includes(norm(document.querySelector("#eng-answer").value));if(ok){document.querySelector("#eng-feedback").textContent="⭐ Richtig! +10 XP";const p=profile();p.xp+=10;p.today++;p.englishCount++;saveDB();renderHome();burst("⭐");setTimeout(()=>{engPos++;renderEnglish()},500)}else{document.querySelector("#eng-feedback").innerHTML=`Fast. Richtig wäre: <b>${w.en}</b>`;shake(document.querySelector(".learn-card"))}};
document.querySelector("#eng-answer").onkeydown=e=>{if(e.key==="Enter")document.querySelector("#eng-check").click()};
document.querySelector("#eng-dontknow").onclick=()=>{const w=engSession[engPos];if(w)document.querySelector("#eng-feedback").innerHTML=`Kein Problem. Richtig ist: <b>${w.en}</b>`};
document.querySelector("#eng-hint").onclick=()=>{const w=engSession[engPos];if(!w)return;const c=norm(w.en).replace(/^(the|a|an|to)\s+/,"");const known={like:"Denk an den Like-Button.",house:"Klingt fast wie Haus.",dog:"Denk an die Dogge.",read:"Denk an einen E-Reader.",bike:"Denk an Mountainbike.",apple:"Denk an die Firma mit dem Apfel-Logo."};document.querySelector("#eng-hint-text").textContent=known[c]||`Das Hauptwort beginnt mit „${c.charAt(0).toUpperCase()}“.`};
loadWords();
